// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkzPondbvEc2QjzBdN5RmTv0s2Ltuf7XE',
    appId: '1:794687222646:web:314db9e294ccb6f2744057',
    messagingSenderId: '794687222646',
    projectId: 'safety-8b634',
    authDomain: 'safety-8b634.firebaseapp.com',
    storageBucket: 'safety-8b634.appspot.com',
    measurementId: 'G-5ZX979EPZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxOI-JSTx0q8E1xPqV_f2Dxdk5xq4AQO0',
    appId: '1:794687222646:android:697d90dffb99428e744057',
    messagingSenderId: '794687222646',
    projectId: 'safety-8b634',
    storageBucket: 'safety-8b634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDimzUAGUEXqG5BgPXzdK9VkN0jtKJQKzQ',
    appId: '1:794687222646:ios:94a0e3d53c0742e9744057',
    messagingSenderId: '794687222646',
    projectId: 'safety-8b634',
    storageBucket: 'safety-8b634.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDimzUAGUEXqG5BgPXzdK9VkN0jtKJQKzQ',
    appId: '1:794687222646:ios:94a0e3d53c0742e9744057',
    messagingSenderId: '794687222646',
    projectId: 'safety-8b634',
    storageBucket: 'safety-8b634.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkzPondbvEc2QjzBdN5RmTv0s2Ltuf7XE',
    appId: '1:794687222646:web:c2c3296ef6b90434744057',
    messagingSenderId: '794687222646',
    projectId: 'safety-8b634',
    authDomain: 'safety-8b634.firebaseapp.com',
    storageBucket: 'safety-8b634.appspot.com',
    measurementId: 'G-W8LVKLLT2Q',
  );
}
